
USE POLYMART_v1
GO

-- lấy số id tiếp theo của bảng
IF OBJECT_ID('PROC_GETID') IS NOT NULL
DROP PROC PROC_GETID
GO
CREATE PROC PROC_GETID
	@TABLE_NAME VARCHAR(30)
AS
	IF(@TABLE_NAME IS NULL)
		PRINT N'DỮ LIỆU NHẬP VÀO KHÔNG HỢP LỆ'
	ELSE
		DECLARE @LASSTID INT
		SET @LASSTID = IDENT_CURRENT(@TABLE_NAME)
		SELECT @LASSTID

-- CẬP NHẬT LẠI SỐ LƯỢNG TỒN KHO SAU KHI XÓA HÓA ĐƠN NHẬP HÀNG
-- xóa hóa đơn nhập hàng
IF OBJECT_ID('PROC_DELETE_HOADONNHAPHANG') IS NOT NULL
DROP PROC PROC_DELETE_HOADONNHAPHANG
GO
CREATE PROC PROC_DELETE_HOADONNHAPHANG
	@IDHOADONNHAPHANG INT
AS
	BEGIN TRY
		BEGIN TRAN
			IF (@IDHOADONNHAPHANG NOT IN (SELECT ID FROM HOADONNHAPHANG))
				PRINT N'MÃ HÓA ĐƠN KHÔNG TỒN TẠI'
			ELSE
				UPDATE CHITIETSANPHAM 
				SET SOLUONG = SOLUONG - (SELECT SOLUONG FROM CHITIETHOADONNHAPHANG 
					WHERE IDCHITIETSANPHAM = CHITIETSANPHAM.ID AND IDHOADONNHAPHANG = @IDHOADONNHAPHANG)
				WHERE ID IN (SELECT IDCHITIETSANPHAM FROM CHITIETHOADONNHAPHANG 
					WHERE IDHOADONNHAPHANG = @IDHOADONNHAPHANG)
				DELETE FROM CHITIETHOADONNHAPHANG
				WHERE IDHOADONNHAPHANG = @IDHOADONNHAPHANG
				DELETE FROM HOADONNHAPHANG WHERE ID = @IDHOADONNHAPHANG
		COMMIT TRAN
	END TRY
	BEGIN CATCH
		ROLLBACK TRAN
	END CATCH


-- CẬP NHẬT LẠI SỐ LƯỢNG TỒN KHO SAU KHI XÓA HÓA ĐƠN THANH TOÁN
-- xóa hóa đơn thanh toán
IF OBJECT_ID('PROC_DELETE_HOADONTHANHTOAN') IS NOT NULL
DROP PROC PROC_DELETE_HOADONTHANHTOAN
GO
CREATE PROC PROC_DELETE_HOADONTHANHTOAN
	@IDHOADONTHANHTOAN INT
AS
	BEGIN TRY
		BEGIN TRAN
			IF (@IDHOADONTHANHTOAN NOT IN (SELECT ID FROM HOADONTHANHTOAN))
				PRINT N'MÃ HÓA ĐƠN KHÔNG TỒN TẠI'
			ELSE
				UPDATE CHITIETSANPHAM 
				SET SOLUONG = SOLUONG + (SELECT SOLUONG FROM CHITIETHOADONTHANHTOAN 
					WHERE IDCHITIETSANPHAM = CHITIETSANPHAM.ID AND IDHOADONTHANHTOAN = @IDHOADONTHANHTOAN)
				WHERE ID IN (SELECT IDCHITIETSANPHAM FROM CHITIETHOADONTHANHTOAN 
					WHERE IDHOADONTHANHTOAN = @IDHOADONTHANHTOAN)
				DELETE FROM CHITIETHOADONTHANHTOAN
				WHERE IDHOADONTHANHTOAN = @IDHOADONTHANHTOAN
				DELETE FROM HOADONTHANHTOAN WHERE ID = @IDHOADONTHANHTOAN
		COMMIT TRAN
	END TRY
	BEGIN CATCH
		ROLLBACK TRAN
	END CATCH


-- CẬP NHẬT LẠI SỐ LƯỢNG TỒN KHO SAU KHI XÓA HÓA ĐƠN TRẢ HÀNG
-- xóa hóa đơn trả hàng
IF OBJECT_ID('PROC_DELETE_HOADONTRAHANG') IS NOT NULL
DROP PROC PROC_DELETE_HOADONTRAHANG
GO
CREATE PROC PROC_DELETE_HOADONTRAHANG
	@IDHOADONTRAHANG INT
AS
	BEGIN TRY
		BEGIN TRAN
			IF (@IDHOADONTRAHANG NOT IN (SELECT ID FROM HOADONTRAHANG))
				PRINT N'MÃ HÓA ĐƠN KHÔNG TỒN TẠI'
			ELSE
				UPDATE CHITIETSANPHAM 
				SET SOLUONG = SOLUONG - (SELECT CTHDTH.SOLUONG FROM CHITIETHOADONTRAHANG AS CTHDTH JOIN CHITIETHOADONTHANHTOAN AS CTHDTT
					ON CTHDTH.IDCHITIETHOADONTHANHTOAN = CTHDTT.ID JOIN HOADONTRAHANG AS HDTH
					ON CTHDTH.IDHOADONTRAHANG = HDTH.ID
					WHERE CTHDTT.IDCHITIETSANPHAM = CHITIETSANPHAM.ID AND CTHDTH.IDHOADONTRAHANG = @IDHOADONTRAHANG)
				WHERE ID IN (SELECT CTHDTT.IDCHITIETSANPHAM FROM CHITIETHOADONTRAHANG AS CTHDTH JOIN CHITIETHOADONTHANHTOAN AS CTHDTT
					ON CTHDTH.IDCHITIETHOADONTHANHTOAN = CTHDTT.ID JOIN HOADONTRAHANG AS HDTH
					ON CTHDTH.IDHOADONTRAHANG = HDTH.ID
					WHERE CTHDTH.IDHOADONTRAHANG = @IDHOADONTRAHANG)
				DELETE FROM CHITIETHOADONTRAHANG
				WHERE IDHOADONTRAHANG = @IDHOADONTRAHANG
				DELETE FROM HOADONTRAHANG WHERE ID = @IDHOADONTRAHANG
		COMMIT TRAN
	END TRY
	BEGIN CATCH
		ROLLBACK TRAN
	END CATCH

-- LẤY DATA GET DỮ LIỆU BẢNG HÓA ĐƠN TRẢ HÀNG
IF OBJECT_ID('PROC_SHOWTABLE_TRAHANG') IS NOT NULL
DROP PROC PROC_SHOWTABLE_TRAHANG
GO
CREATE PROC PROC_SHOWTABLE_TRAHANG
	@IDTRAHANG INT
AS
	IF @IDTRAHANG NOT IN (SELECT ID FROM HOADONTRAHANG)
		PRINT N'HÓA ĐƠN KHÔNG TỒN TẠI'
	ELSE
		SELECT HDTH.ID, CTHDTT.IDHOADONTHANHTOAN, HDTH.NGAYTRAHANG, HDTT.IDKHACHHANG,
		CTHDTH.SOLUONG * (CTSP.GIABAN - CTSP.GIAGIAM) AS TONGTIEN, HDTH.GHICHU
		FROM HOADONTRAHANG AS HDTH JOIN CHITIETHOADONTRAHANG AS CTHDTH
		ON HDTH.ID = CTHDTH.IDHOADONTRAHANG JOIN CHITIETHOADONTHANHTOAN AS CTHDTT
		ON CTHDTH.IDCHITIETHOADONTHANHTOAN = CTHDTT.ID JOIN HOADONTHANHTOAN AS HDTT
		ON CTHDTT.IDHOADONTHANHTOAN = HDTT.ID JOIN CHITIETSANPHAM AS CTSP
		ON CTHDTT.IDCHITIETSANPHAM = CTSP.ID
		WHERE HDTH.ID = @IDTRAHANG



