

USE POLYMART_v1
GO

-- Thống kê doanh thu
IF OBJECT_ID('THONG_KE_DOANH_THU') IS NOT NULL
DROP PROC THONG_KE_DOANH_THU
GO
CREATE PROC THONG_KE_DOANH_THU
	@YEAR INT,
	@MONTH INT
AS
	DECLARE @ID_THEOTHANG TABLE(
		ID INT,
		DIEMDADOI INT
	)
	INSERT INTO @ID_THEOTHANG SELECT ID, DIEMDADOI FROM HOADONTHANHTOAN WHERE YEAR(NGAYTHANHTOAN) = @YEAR AND MONTH(NGAYTHANHTOAN) = @MONTH
    SELECT SUM((GIABAN - GIAVON - CHITIETHOADONTHANHTOAN.GIAMGIATHEM - DIEMDADOI) * CHITIETHOADONTHANHTOAN.SOLUONG) AS DOANHTHU, 
    SUM(CHITIETHOADONTHANHTOAN.SOLUONG) AS SOLUONGBAN
    FROM CHITIETHOADONTHANHTOAN JOIN CHITIETSANPHAM 
    ON CHITIETHOADONTHANHTOAN.IDCHITIETSANPHAM = CHITIETSANPHAM.ID 
	JOIN @ID_THEOTHANG AS IDTHEOTHANG ON IDTHEOTHANG.ID = CHITIETHOADONTHANHTOAN.IDHOADONTHANHTOAN

exec THONG_KE_DOANH_THU 2021, 4
GO

-- Thống kê doanh so
IF OBJECT_ID('THONG_KE_DOANH_SO') IS NOT NULL
DROP PROC THONG_KE_DOANH_SO
GO
CREATE PROC THONG_KE_DOANH_SO
	@YEAR INT,
	@MONTH INT
AS

	DECLARE @THONGKEDOANHSO TABLE (
		IDCHITIETSP INT,
		SOLUONGBAN INT
	)

	INSERT INTO @THONGKEDOANHSO 
    SELECT IDCHITIETSANPHAM, SUM(SOLUONG) AS SOLUONGBAN FROM 
	CHITIETHOADONTHANHTOAN JOIN HOADONTHANHTOAN 
	ON CHITIETHOADONTHANHTOAN.IDHOADONTHANHTOAN = HOADONTHANHTOAN.ID
	WHERE YEAR(NGAYTHANHTOAN) = @YEAR AND MONTH(NGAYTHANHTOAN) = @MONTH
	GROUP BY IDCHITIETSANPHAM

	SELECT SANPHAM.ID, TEN, SUM(SOLUONGBAN) AS SOLUONGBAN FROM SANPHAM JOIN CHITIETSANPHAM ON SANPHAM.ID = CHITIETSANPHAM.IDSANPHAM
	JOIN @THONGKEDOANHSO AS THONGKE ON THONGKE.IDCHITIETSP = CHITIETSANPHAM.ID
	GROUP BY SANPHAM.ID, TEN
	ORDER BY SOLUONGBAN ASC
GO

EXEC THONG_KE_DOANH_SO 2021, 4
-- lấy số id tiếp theo của bảng
IF OBJECT_ID('PROC_GETID') IS NOT NULL
DROP PROC PROC_GETID
GO
CREATE PROC PROC_GETID
	@TABLE_NAME VARCHAR(30)
AS
	IF(@TABLE_NAME IS NULL)
		PRINT N'DỮ LIỆU NHẬP VÀO KHÔNG HỢP LỆ'
	ELSE
		DECLARE @LASSTID INT
		SET @LASSTID = IDENT_CURRENT(@TABLE_NAME)
		SELECT @LASSTID
GO

-- INSERT CHI TIẾT HÓA ĐƠN NHẬP HÀNG
IF OBJECT_ID('PROC_INSERT_CTHOADONNHAPHANG') IS NOT NULL
DROP PROC PROC_INSERT_CTHOADONNHAPHANG
GO
CREATE PROC PROC_INSERT_CTHOADONNHAPHANG
	@IDHOADONNHAPHANG INT,
	@IDCHITIETSANPHAM INT,
	@GIANHAP MONEY,
	@SOLUONG INT
AS
	BEGIN TRY
		BEGIN TRAN
			IF (@IDHOADONNHAPHANG NOT IN (SELECT ID FROM HOADONNHAPHANG)
				OR @IDCHITIETSANPHAM NOT IN (SELECT ID FROM CHITIETSANPHAM))
				PRINT N'MÃ HÓA ĐƠN HOẶC SẢN PHẨM KHÔNG TÒN TẠI'
			ELSE
				IF (@GIANHAP < 1 OR @SOLUONG < 1)
					PRINT N'DỮ LIỆU NHẬP VÀO SAI'
				ELSE
					BEGIN
						DECLARE @ROW INT
						-- INSERT CHI TIẾT HÓA ĐƠN NHẬP
						INSERT INTO CHITIETHOADONNHAPHANG (IDHOADONNHAPHANG, IDCHITIETSANPHAM, GIANHAP, SOLUONG)
						VALUES (@IDHOADONNHAPHANG, @IDCHITIETSANPHAM, @GIANHAP, @SOLUONG)
						-- GET ROWS COUNT INSERT TABLE
						SELECT @ROW  = @@ROWCOUNT
						IF ((SELECT @ROW AS ROW) > 0)
							-- UPDATE TỒN KHO
							UPDATE CHITIETSANPHAM SET GIAVON = ((GIAVON * SOLUONG) + (@GIANHAP * @SOLUONG)) / (SOLUONG + @SOLUONG),
							SOLUONG = SOLUONG + @SOLUONG
							WHERE ID = @IDCHITIETSANPHAM
						ELSE
							ROLLBACK TRAN
					END
		COMMIT TRAN
	END TRY
	BEGIN CATCH
		ROLLBACK TRAN
	END CATCH

GO
-- CẬP NHẬT LẠI SỐ LƯỢNG TỒN KHO SAU KHI XÓA HÓA ĐƠN NHẬP HÀNG
-- xóa hóa đơn nhập hàng
IF OBJECT_ID('PROC_DELETE_HOADONNHAPHANG') IS NOT NULL
DROP PROC PROC_DELETE_HOADONNHAPHANG
GO
CREATE PROC PROC_DELETE_HOADONNHAPHANG
	@IDHOADONNHAPHANG INT
AS
	BEGIN TRY
		BEGIN TRAN
			IF (@IDHOADONNHAPHANG NOT IN (SELECT ID FROM HOADONNHAPHANG))
				PRINT N'MÃ HÓA ĐƠN KHÔNG TỒN TẠI'
			ELSE
				BEGIN
					UPDATE CHITIETSANPHAM 
					-- UPDATE GIÁ VỐN
					SET GIAVON = ((GIAVON * SOLUONG) - (SELECT GIANHAP * SOLUONG FROM CHITIETHOADONNHAPHANG
						WHERE IDCHITIETSANPHAM = CHITIETSANPHAM.ID AND IDHOADONNHAPHANG = @IDHOADONNHAPHANG))/
						(SOLUONG - (SELECT SOLUONG FROM CHITIETHOADONNHAPHANG 
						WHERE IDCHITIETSANPHAM = CHITIETSANPHAM.ID AND IDHOADONNHAPHANG = @IDHOADONNHAPHANG)),
					-- UPDATE SỐ LƯỢNG TỒN KHO
					SOLUONG = SOLUONG - (SELECT SOLUONG FROM CHITIETHOADONNHAPHANG 
						WHERE IDCHITIETSANPHAM = CHITIETSANPHAM.ID AND IDHOADONNHAPHANG = @IDHOADONNHAPHANG)
					WHERE ID IN (SELECT IDCHITIETSANPHAM FROM CHITIETHOADONNHAPHANG 
						WHERE IDHOADONNHAPHANG = @IDHOADONNHAPHANG)
					-- XÓA CHI TIÊT HÓA ĐƠN NHẬP HÀNG
					DELETE FROM CHITIETHOADONNHAPHANG
					WHERE IDHOADONNHAPHANG = @IDHOADONNHAPHANG
					-- XÓA HÓA ĐƠN NHẬP HÀNG
					DELETE FROM HOADONNHAPHANG WHERE ID = @IDHOADONNHAPHANG
				END
		COMMIT TRAN
	END TRY
	BEGIN CATCH
		ROLLBACK TRAN
	END CATCH

GO

-- INSERT CHI TIẾT HÓA ĐƠN TRẢ HÀNG
IF OBJECT_ID('PROC_INSERT_CTHOADONTRAHANG') IS NOT NULL
DROP PROC PROC_INSERT_CTHOADONTRAHANG
GO
CREATE PROC PROC_INSERT_CTHOADONTRAHANG
	@IDHOADONTRAHANG INT,
	@IDCHITIETHOADONTHANHTOAN INT,
	@SOLUONG INT
AS
	BEGIN TRY
		BEGIN TRAN
			IF (@IDHOADONTRAHANG NOT IN (SELECT ID FROM HOADONTRAHANG)
				OR @IDCHITIETHOADONTHANHTOAN NOT IN (SELECT ID FROM CHITIETHOADONTHANHTOAN))
				PRINT N'MÃ SẢN PHẨM HOẶC MÃ HÓA ĐƠN SAI'
			ELSE
				IF (@SOLUONG < 0)
					PRINT N'DỮ LIỆU NHẬP VÀO SAI'
				ELSE
					BEGIN
						DECLARE @ROW INT
						INSERT INTO CHITIETHOADONTRAHANG (IDHOADONTRAHANG, IDCHITIETHOADONTHANHTOAN, SOLUONG)
						VALUES (@IDHOADONTRAHANG, @IDCHITIETHOADONTHANHTOAN, @SOLUONG)
						SELECT @ROW = @@ROWCOUNT
						IF ((SELECT @ROW) > 0)
							BEGIN
								-- CẬP NHẬT CHI TIẾT HÓA ĐƠN THANH TOÁN
								UPDATE CHITIETHOADONTHANHTOAN
								SET SOLUONG = SOLUONG - @SOLUONG
								WHERE ID = @IDCHITIETHOADONTHANHTOAN
								-- CẬP NHẬT CHI TIẾT SẢN PHẨM
								UPDATE CHITIETSANPHAM
								SET SOLUONG = SOLUONG + @SOLUONG
								WHERE ID = (
									SELECT IDCHITIETSANPHAM FROM CHITIETHOADONTHANHTOAN JOIN CHITIETSANPHAM
									ON CHITIETHOADONTHANHTOAN.IDCHITIETSANPHAM = CHITIETSANPHAM.ID
									WHERE CHITIETHOADONTHANHTOAN.ID = @IDCHITIETHOADONTHANHTOAN
								)
							END
						ELSE
							ROLLBACK TRAN
					END
		COMMIT TRAN
	END TRY
	BEGIN CATCH
		ROLLBACK TRAN
	END CATCH
GO

-- INSERT CHI TIẾT HÓA ĐƠN THANH TOÁN
IF OBJECT_ID('PROC_INSERT_CTHOADONTHANHTOAN') IS NOT NULL
DROP PROC PROC_INSERT_CTHOADONTHANHTOAN
GO
CREATE PROC PROC_INSERT_CTHOADONTHANHTOAN
	@IDHOADONTHANHTOAN INT,
	@IDCHITIETSANPHAM INT,
	@GIAGIAMTHEM MONEY, 
	@SOLUONG INT
AS
	BEGIN TRY
		BEGIN TRAN
			IF (@IDHOADONTHANHTOAN NOT IN (SELECT ID FROM HOADONTHANHTOAN)
				OR @IDCHITIETSANPHAM NOT IN (SELECT ID FROM CHITIETSANPHAM))
				PRINT N'MÃ SẢN PHẨM HOẶC HÓA ĐƠN SAI'
			ELSE
				IF (@GIAGIAMTHEM < 0 OR @SOLUONG < 1)
					PRINT N'DỮ LIỆU NHẬP KHÔNG ĐÚNG'
				ELSE
					BEGIN
						DECLARE @ROW INT
						INSERT INTO CHITIETHOADONTHANHTOAN (IDHOADONTHANHTOAN, IDCHITIETSANPHAM, GIAMGIATHEM, SOLUONG)
						VALUES (@IDHOADONTHANHTOAN, @IDCHITIETSANPHAM, @GIAGIAMTHEM, @SOLUONG)
						SELECT @ROW = @@ROWCOUNT
						IF ((SELECT @ROW) < 1)
							ROLLBACK TRAN
						ELSE
							IF ((SELECT (SOLUONG - @SOLUONG) AS TONKHO FROM CHITIETSANPHAM WHERE ID = @IDCHITIETSANPHAM) < 0)
								BEGIN
									PRINT N'TỒN KHO KHÔNG ĐỦ'
									ROLLBACK TRAN
								END
							ELSE
								-- CẬP NHẬT SỐ LƯỢNG TỒN KHO
								UPDATE CHITIETSANPHAM
								SET SOLUONG = SOLUONG - @SOLUONG
								WHERE ID = @IDCHITIETSANPHAM
					END
		COMMIT TRAN
	END TRY
	BEGIN CATCH
		ROLLBACK TRAN
	END CATCH

GO

-- CẬP NHẬT LẠI SỐ LƯỢNG TỒN KHO SAU KHI XÓA HÓA ĐƠN THANH TOÁN
-- xóa hóa đơn thanh toán
IF OBJECT_ID('PROC_DELETE_HOADONTHANHTOAN') IS NOT NULL
DROP PROC PROC_DELETE_HOADONTHANHTOAN
GO
CREATE PROC PROC_DELETE_HOADONTHANHTOAN
	@IDHOADONTHANHTOAN INT
AS
	BEGIN TRY
		BEGIN TRAN
			IF (@IDHOADONTHANHTOAN NOT IN (SELECT ID FROM HOADONTHANHTOAN))
				PRINT N'MÃ HÓA ĐƠN KHÔNG TỒN TẠI'
			ELSE
				BEGIN
					UPDATE CHITIETSANPHAM 
					SET SOLUONG = SOLUONG + (SELECT SOLUONG FROM CHITIETHOADONTHANHTOAN 
						WHERE IDCHITIETSANPHAM = CHITIETSANPHAM.ID AND IDHOADONTHANHTOAN = @IDHOADONTHANHTOAN)
					WHERE ID IN (SELECT IDCHITIETSANPHAM FROM CHITIETHOADONTHANHTOAN 
						WHERE IDHOADONTHANHTOAN = @IDHOADONTHANHTOAN)
					DELETE FROM CHITIETHOADONTHANHTOAN
					WHERE IDHOADONTHANHTOAN = @IDHOADONTHANHTOAN
					DELETE FROM HOADONTHANHTOAN WHERE ID = @IDHOADONTHANHTOAN
				END
		COMMIT TRAN
	END TRY
	BEGIN CATCH
		ROLLBACK TRAN
	END CATCH

GO

-- CẬP NHẬT LẠI SỐ LƯỢNG TỒN KHO SAU KHI XÓA HÓA ĐƠN TRẢ HÀNG
-- xóa hóa đơn trả hàng
IF OBJECT_ID('PROC_DELETE_HOADONTRAHANG') IS NOT NULL
DROP PROC PROC_DELETE_HOADONTRAHANG
GO
CREATE PROC PROC_DELETE_HOADONTRAHANG
	@IDHOADONTRAHANG INT
AS
	BEGIN TRY
		BEGIN TRAN
			IF (@IDHOADONTRAHANG NOT IN (SELECT ID FROM HOADONTRAHANG))
				PRINT N'MÃ HÓA ĐƠN KHÔNG TỒN TẠI'
			ELSE
				BEGIN
					-- CẬP NHẬT SỐ LƯỢNG CHI TIẾT SẢN PHẨM
					UPDATE CHITIETSANPHAM 
					SET SOLUONG = SOLUONG - (
						SELECT CTHDTH.SOLUONG FROM CHITIETHOADONTRAHANG AS CTHDTH JOIN CHITIETHOADONTHANHTOAN AS CTHDTT
						ON CTHDTH.IDCHITIETHOADONTHANHTOAN = CTHDTT.ID JOIN HOADONTRAHANG AS HDTH
						ON CTHDTH.IDHOADONTRAHANG = HDTH.ID
						WHERE CTHDTT.IDCHITIETSANPHAM = CHITIETSANPHAM.ID AND CTHDTH.IDHOADONTRAHANG = @IDHOADONTRAHANG
					)
					WHERE ID IN (
						SELECT CTHDTT.IDCHITIETSANPHAM FROM CHITIETHOADONTRAHANG AS CTHDTH JOIN CHITIETHOADONTHANHTOAN AS CTHDTT
						ON CTHDTH.IDCHITIETHOADONTHANHTOAN = CTHDTT.ID JOIN HOADONTRAHANG AS HDTH
						ON CTHDTH.IDHOADONTRAHANG = HDTH.ID
						WHERE CTHDTH.IDHOADONTRAHANG = @IDHOADONTRAHANG
					)

					-- CẬP NHẬT SỐ LƯỢNG HÓA ĐƠN THANH TOÁN
					UPDATE CHITIETHOADONTHANHTOAN
					SET SOLUONG = SOLUONG + (
						SELECT CTHDTH.SOLUONG FROM CHITIETHOADONTRAHANG AS CTHDTH JOIN HOADONTRAHANG AS HDTH
						ON HDTH.ID = CTHDTH.IDHOADONTRAHANG
						WHERE CTHDTH.IDCHITIETHOADONTHANHTOAN = CHITIETHOADONTHANHTOAN.ID AND HDTH.ID = @IDHOADONTRAHANG
					)
					WHERE ID IN (
						SELECT CTHDTH.IDCHITIETHOADONTHANHTOAN FROM CHITIETHOADONTRAHANG AS CTHDTH JOIN HOADONTRAHANG AS HDTH
						ON CTHDTH.IDHOADONTRAHANG = HDTH.ID
						WHERE HDTH.ID = @IDHOADONTRAHANG
					)

					-- DELETE CHITIETHOADONTRAHANG
					DELETE FROM CHITIETHOADONTRAHANG
					WHERE IDHOADONTRAHANG = @IDHOADONTRAHANG

					-- DELETE HOADONTRAHANG
					DELETE FROM HOADONTRAHANG WHERE ID = @IDHOADONTRAHANG
				END
		COMMIT TRAN
	END TRY
	BEGIN CATCH
		PRINT N'LỖI'
		ROLLBACK TRAN
	END CATCH

GO

-- LẤY DATA GET DỮ LIỆU BẢNG HÓA ĐƠN TRẢ HÀNG
IF OBJECT_ID('PROC_SHOWTABLE_TRAHANG') IS NOT NULL
DROP PROC PROC_SHOWTABLE_TRAHANG
GO
CREATE PROC PROC_SHOWTABLE_TRAHANG
	@IDTRAHANG INT
AS
	IF @IDTRAHANG NOT IN (SELECT ID FROM HOADONTRAHANG)
		PRINT N'HÓA ĐƠN KHÔNG TỒN TẠI'
	ELSE
		SELECT HDTH.ID, CTHDTT.IDHOADONTHANHTOAN, HDTH.NGAYTRAHANG, KH.HOTEN,
		SUM(CTHDTH.SOLUONG * (CTSP.GIABAN - CTSP.GIAGIAM)) AS TONGTIEN
		FROM HOADONTRAHANG AS HDTH JOIN CHITIETHOADONTRAHANG AS CTHDTH
		ON HDTH.ID = CTHDTH.IDHOADONTRAHANG JOIN CHITIETHOADONTHANHTOAN AS CTHDTT
		ON CTHDTH.IDCHITIETHOADONTHANHTOAN = CTHDTT.ID JOIN HOADONTHANHTOAN AS HDTT
		ON CTHDTT.IDHOADONTHANHTOAN = HDTT.ID JOIN CHITIETSANPHAM AS CTSP
		ON CTHDTT.IDCHITIETSANPHAM = CTSP.ID JOIN KHACHHANG AS KH
		ON KH.ID = HDTT.IDKHACHHANG
		WHERE HDTH.ID = @IDTRAHANG
		GROUP BY HDTH.ID, CTHDTT.IDHOADONTHANHTOAN, HDTH.NGAYTRAHANG, KH.HOTEN

